# Generated by Django 6.1 on 2026-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='close_friends_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('close_friends', 'Close Friends only'), ('top_friends', 'Top Friends only'), ('only_me', 'Only me')], default='only_me', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('close_friends', 'Close Friends only'), ('top_friends', 'Top Friends only'), ('only_me', 'Only me')], default='friends', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_friends_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('close_friends', 'Close Friends only'), ('top_friends', 'Top Friends only'), ('only_me', 'Only me')], default='public', max_length=20),
        ),
    ]
