# Generated by Django 6.1 on 2026-10-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def award_existing_badges(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    ProfileBadge = apps.get_model("profiles", "ProfileBadge")
    Interest = apps.get_model("profiles", "Interest")
    Post = apps.get_model("Posting", "Post")
    Comment = apps.get_model("Posting", "Comment")
    Friendship = apps.get_model("friends", "Friendship")
    database = schema_editor.connection.alias

    for profile in Profile.objects.using(database).all().iterator():
        user_id = profile.user_id
        earned_badges = []
        if Post.objects.using(database).filter(author_id=user_id).exists():
            earned_badges.append("first_post")
        if Comment.objects.using(database).filter(author_id=user_id).exists():
            earned_badges.append("conversation_starter")
        if Friendship.objects.using(database).filter(user_id=user_id).exists():
            earned_badges.append("connector")
        if (
            Interest.objects.using(database).filter(profile_id=profile.pk).exists()
            or profile.avatar != "avatars/default.png"
        ):
            earned_badges.append("profile_stylist")

        ProfileBadge.objects.using(database).bulk_create(
            [
                ProfileBadge(profile_id=profile.pk, badge=badge)
                for badge in earned_badges
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilevisit'),
        ('Posting', '0009_alter_post_content'),
        ('friends', '0003_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_streaks_badges',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('login', 'Daily login'), ('post', 'Daily posting')], max_length=10)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'activity'), name='unique_user_daily_streak')],
            },
        ),
        migrations.CreateModel(
            name='ProfileBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('first_post', 'First Post'), ('conversation_starter', 'Conversation Starter'), ('connector', 'Connector'), ('profile_stylist', 'Profile Stylist')], max_length=24)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='profiles.profile')),
            ],
            options={
                'ordering': ['earned_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'badge'), name='unique_profile_badge')],
            },
        ),
        migrations.RunPython(award_existing_badges, migrations.RunPython.noop),
    ]
