# Generated by Django 6.1 on 2026-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_show_streaks_badges_dailystreak_profilebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_frame',
            field=models.CharField(choices=[('classic', 'Classic'), ('gold', 'Golden'), ('neon', 'Neon'), ('floral', 'Floral'), ('pixel', 'Pixel'), ('none', 'No frame')], default='classic', max_length=12),
        ),
    ]
