# Generated by Django 6.1 on 2026-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_avatar_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_frame',
            field=models.CharField(choices=[('classic', 'Classic'), ('gold', 'Golden'), ('neon', 'Neon'), ('floral', 'Floral'), ('pixel', 'Pixel'), ('starburst', 'Starburst'), ('crystal', 'Prismatic Crystal'), ('glitch', 'Glitch'), ('liquid', 'Alien Bloom'), ('orbit', 'Orbiting Satellites'), ('none', 'No frame')], default='classic', max_length=12),
        ),
    ]
