# Generated by Django 6.1 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_avatar_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sticker_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Sticker positions as percentages, keyed by sticker name.'),
        ),
    ]
