# Generated by Django 6.1 on 2026-10-07 14:19

from django.db import migrations, models


def create_default_stickers(apps, schema_editor):
    Sticker = apps.get_model("profiles", "Sticker")
    stickers = [
        ("star", "Star", "⭐", 0),
        ("heart", "Heart", "💖", 1),
        ("sparkle", "Sparkle", "✨", 2),
        ("flower", "Flower", "🌸", 3),
        ("planet", "Planet", "🪐", 4),
    ]
    Sticker.objects.using(schema_editor.connection.alias).bulk_create([
        Sticker(
            key=key,
            name=name,
            emoji=emoji,
            is_active=True,
            sort_order=sort_order,
        )
        for key, name, emoji, sort_order in stickers
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_sticker_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(create_default_stickers, migrations.RunPython.noop),
    ]
