# Generated by Django 6.1 on 2026-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, upload_to='profile_banners/'),
        ),
    ]
