# Generated by Django 6.1 on 2026-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
