# Generated by Django 6.1 on 2026-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0002_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('permanent', 'Permanent Post'), ('flash', '24-Hour Flash Post')], default='permanent', max_length=10),
        ),
    ]
