# Generated by Django 6.1 on 2026-10-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0008_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
