# Generated by Django 6.1 on 2026-10-05 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0004_post_visibility'),
        ('user_controls', '0002_block_restriction_seeless'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('blocked_user')), _negated=True), name='block_cannot_target_self'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reported_post__isnull', True), ('reported_user__isnull', False)), models.Q(('reported_post__isnull', False), ('reported_user__isnull', True)), _connector='OR'), name='report_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='restriction',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('restricted_user')), _negated=True), name='restriction_cannot_target_self'),
        ),
        migrations.AddConstraint(
            model_name='seeless',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('target_user')), _negated=True), name='see_less_cannot_target_self'),
        ),
    ]
