# Generated by Django 6.1 on 2026-09-09 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0002_post_updated_at'),
        ('userreport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment, bullying, or hate speech'), ('spam', 'Spam'), ('scam', 'Scam or fraud'), ('misinfo', 'Misinformation'), ('inappropriate', 'Inappropriate or explicit content'), ('other', 'Something else')], max_length=50)),
                ('context', models.TextField(blank=True, help_text='Add extra details (Optional).')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Posting.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment, bullying, or hate speech'), ('spam', 'Spam'), ('scam', 'Scam or fraud'), ('misinfo', 'Misinformation'), ('inappropriate', 'Inappropriate or explicit content'), ('other', 'Something else')], max_length=50)),
                ('context', models.TextField(blank=True, help_text='Add extra details (Optional).')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
