# Generated by Django 6.1 on 2026-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreport', '0002_postreport_userreport_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreport',
            old_name='reported_post',
            new_name='post',
        ),
    ]
