# Generated by Django 6.1 on 2026-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_private_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('classic', 'Nexolotl original'), ('dark', 'Midnight'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset')], default='classic', max_length=12),
        ),
    ]
