# Generated by Django 6.1 on 2026-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('classic', 'Nexolotl original'), ('dark', 'Midnight'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('sakura', 'Sakura')], default='classic', max_length=12),
        ),
    ]
