# Generated by Django 6.1 on 2026-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('classic', 'Nexolotl Breeze'), ('dark', 'Midnight'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('sakura', 'Sakura'), ('sage', 'Sage'), ('slate', 'Slate'), ('sky', 'Sky'), ('neon', 'Neon'), ('electric', 'Electric'), ('abyss', 'Abyss'), ('harbor', 'Harbor')], default='classic', max_length=12),
        ),
    ]
