# Generated by Django 6.1 on 2026-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
