# Generated by Django 6.1 on 2026-09-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment, bullying, or hate speech'), ('misinformation', 'Misinformation'), ('spam', 'Spam'), ('scam', 'Scam or fraud'), ('violent', 'Violent material'), ('sexual', 'Sexual material'), ('other', 'Something else')], max_length=50)),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
