# Generated by Django 6.1 on 2026-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_testimonies_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
